### ISSUE TITLE
Load Templates button not loading any templates

### ISSUE THREAD

**Issue by Biz1976** [MscrmTools/MscrmTools.DocumentTemplatesMover-#10]
Hi - I have successfully connected to our environment, however, when I press the "Load Templates" button - nothing happens and the list / box remains blank - i.e. no templates appear.  Please can someone advise what we need to do?

**Comment by MscrmTools** [comment]
The tool loads only custom template, not the one created by the account SYSTEM.
I will add a warning when no custom template found
