### ISSUE TITLE
Header/Footer not updated with target entity object code

### ISSUE THREAD

**Issue by oliverfrodrigues** [MscrmTools/MscrmTools.DocumentTemplatesMover-#11]
When moving Word Templates to a new environment, the tool successfully updates the Entity Object Code for the target environment, but only for the body of the document, not for the Header or Footer of the document

**Comment by MscrmTools** [comment]
Can you provide the docx?

**Comment by oliverfrodrigues** [comment]
[WordTemplate.docx](https://github.com/MscrmTools/MscrmTools.DocumentTemplatesMover/files/4224125/WordTemplate.docx)
Word Document attached

**Comment by MscrmTools** [comment]
Thx

**Comment by MscrmTools** [comment]
Can you test with this version?
[MsCrmTools.DocumentTemplatesMover.zip](https://github.com/MscrmTools/MscrmTools.DocumentTemplatesMover/files/4224722/MsCrmTools.DocumentTemplatesMover.zip)

**Comment by oliverfrodrigues** [comment]
Perfect.. that version works fine 😉

**Comment by MscrmTools** [comment]
I will push it on the Tool Library.
Thanks for testing it
