### ISSUE TITLE
Memory Stream is not expanable - error?

### ISSUE THREAD

**Issue by anothersphere** [MscrmTools/MscrmTools.DocumentTemplatesMover-#3]
Tried to use, got a 'Memory Stream is not expandable' error.
On a selection.
On one only.
I deleted any with same name in target.
All got the same error.

What/Why?

**Comment by RobertxRM1** [comment]
my also, same error

**Comment by augustgugi** [comment]
This issue should be fixed with the latest updates.

**Comment by RobertxRM1** [comment]
`??

I believe this is fixed few months ago!?

**Comment by MscrmTools** [comment]
is it fixed then?

**Comment by RobertxRM1** [comment]
????

yes fixed 3 months ago, however I do not know did owner of the application incorporate solution.

by my dev, it was not a fix, it was a workaround, but I manage to migrate  templates from one system to another, correctly after his workaround was applied



Robert Bilic
Dynamics 365 2nd Level
Support Technician

robert.bilic@xRM1.com<mailto:robert.bilic@xRM1.com>
support@xRM1.com<mailto:support@xRM1.com>


xRM1 Business Solutions<http://www.xrm1.com/>
Beethovenstrasse 5c
97080 Würzburg - Germany
Time Zone CEST
A brand of itara group of companies


[AAEAAQAAAAAAAAN_AAAAJDYyNTg0MjY4LTkxYjAtNGQzZi04YjcyLTQzNjU3ZDA1M2FlNA]<http://www.xrm1.com/en/hr-management/index.htm>
[Screenshot066]<http://www.xrm1.com/en/e-learning/index.htm>[support]<http://www.xrm1.com/en/support/index.htm>

**Comment by MscrmTools** [comment]
Ok, the code has been merged but not released. I will do that when I find time

**Comment by RobertxRM1** [comment]
ok

Robert Bilic
Dynamics 365 2nd Level
Support Technician

robert.bilic@xRM1.com<mailto:robert.bilic@xRM1.com>
support@xRM1.com<mailto:support@xRM1.com>


xRM1 Business Solutions<http://www.xrm1.com/>
Beethovenstrasse 5c
97080 Würzburg - Germany
Time Zone CEST
A brand of itara group of companies


[AAEAAQAAAAAAAAN_AAAAJDYyNTg0MjY4LTkxYjAtNGQzZi04YjcyLTQzNjU3ZDA1M2FlNA]<http://www.xrm1.com/en/hr-management/index.htm>
[Screenshot066]<http://www.xrm1.com/en/e-learning/index.htm>[support]<http://www.xrm1.com/en/support/index.htm>

**Comment by OferFel** [comment]
Any update on that?
Still getting the same error message for a custom entity

**Comment by MscrmTools** [comment]
closing issue. Tell me if it is still happening
