### ISSUE TITLE
Error message when opening plugin

### ISSUE THREAD

**Issue by Simplystepx** [MscrmTools/MscrmTools.DocumentTemplatesMover-#6]
Hi,
I am getting the following error when I try to use the plugin
![dtm error](https://user-images.githubusercontent.com/38095476/38350724-e559ffcc-38ef-11e8-84dc-e5bac1756f31.PNG)

It worked previously, however since the latest XrmToolBox update I haven't been able to use it.

**Comment by MscrmTools** [comment]
I will fix this ASAP 

Thanks for reporting it

**Comment by Simplystepx** [comment]
I am still getting the same error message and have done a re-install of the toolbox and no luck... :(
