### ISSUE TITLE
"Unable to read user password" error when transferring to Online Region GCC High Organization

### ISSUE THREAD

**Issue by GaryC79** [MscrmTools/MscrmTools.DocumentTemplatesMover-#9]
Hello, I've been a big fan of this plug-in for some time but I'm getting an error that states "An error has occurred while transferring templates:  Unable to read user password" when trying to move a template to an Online Region GCC High organization.  I have tested the same template using an out of the box entity (Contact) going between GCC DoD and North America.  For the GCC High org, I am able to load the list of templates, but when I am trying to transfer to a GCC High org I receive the error.  I am using the Document Templates Mover plug in version 1.2018.4.3 and XrmToolBox  version 1.2019.7.34.

<img width="386" alt="GCC High Document Template Mover Error" src="https://user-images.githubusercontent.com/57363107/68137192-678b8300-fedb-11e9-867f-ea756d3472c7.png">

**Comment by dmosier** [comment]
We are seeing the same issue with GCC High.  Any idea when this plug-in will support GCC High?

**Comment by MscrmTools** [comment]
Can you test with latest version of XrmToolBox?

**Comment by dmosier** [comment]
I just tried the new version in a GCC High deployment and it worked.

Thanks
